services:
  # Development Environment with Claude Code and VS Code Server
  devenv:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: claude-wp-devenv1
    volumes:
      # Mount the host Docker socket to allow Docker in Docker
      - /var/run/docker.sock:/var/run/docker.sock
      # Mount the WordPress code directory
      - ./wordpress:/home/developer/wordpress
      # Mount any SSH keys (optional)
      - ~/.ssh:/home/developer/.ssh:ro
    ports:
      # VS Code Server port
      - "8085:8085"
      # Additional ports for development
      - "3015:3015"
      - "9019:9019"
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      # Add any other required environment variables
    restart: unless-stopped
    depends_on:
      - db
      - wordpress
    networks:
      - wp-network

  # Nginx Proxy
  nginx:
    image: nginx:latest
    container_name: claude-wp-nginx1
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./config/certs:/etc/nginx/certs
    depends_on:
      - wordpress
    restart: unless-stopped
    networks:
      - wp-network

  # WordPress Container
  wordpress:
    image: wordpress:latest
    container_name: claude-wp-wordpress1
    volumes:
      # Mount WordPress content for direct editing
      - ./wordpress:/var/www/html
      # Custom wp-config
      - ./config/wp-config.php:/var/www/html/wp-config.php
      # Custom PHP configuration
      - ./config/php.ini:/usr/local/etc/php/conf.d/custom.ini
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 1
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - wp-network
  
  # Database Container
  db:
    image: mysql:8.0
    container_name: claude-wp-db1
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql
      - ./config/mysql:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    ports:
      - "13307:3307"
    restart: unless-stopped
    networks:
      - wp-network
  
  # PhpMyAdmin (optional)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: claude-wp-phpmyadmin1
    environment:
      PMA_HOST: db
      PMA_PORT: 3307
    ports:
      - "8082:80"
    depends_on:
      - db
    networks:
      - wp-network

# Persistent Volumes
volumes:
  db_data:
    name: claude-wp-db-data1

# Docker Networks
networks:
  wp-network:
    name: claude-wp-network
    driver: bridge
